added files for the career database
Estyg100/Career pull request #2
Opened 2024-01-01 04:10 UTC by ChavyWal

I did the work please review.

2024-01-01 21:24 UTC, Estyg100 requested changes
Excellent!!!! Amazing Job!!!!!! I'm really impressed with all your great work!!!!!!
I did come across a few changes that I'd like you to make.
Pls have them changed, and resubmit your work.
Thanks so much, and good luck!

2024-01-01 21:24 UTC, Estyg100 commented on 1 Table.sql
> +DateFoundJob Date null ,
Add constraints to the date column**s** ensuring that there are no future dates allowed.

2024-01-01 21:24 UTC, Estyg100 commented on 1 Table.sql
> +    constraint ck_score2_cannot_be_lower_than_score3 check (score2 >= score3),
Tip: You can combine these two constraints using an and. Same goes to the following two constraints. You can also combine those.

2024-01-01 21:24 UTC, Estyg100 commented on 1 Table.sql
> +    constraint u_Phone_number_Has_to_be_unique unique,
It might be helpful to add a constraint ensuring that all the phone numbers are recorded in the proper format, to prevent wrong data (10 digits with the dashes in the right places). After that, the constraint not allowing blank phone numbers will not be necessary.

2024-01-01 21:24 UTC, Estyg100 commented on 3 reports.sql
> +select fullname = CONCAT(c.lastname, ', ', c.Firstname), clusterscore1 = CONCAT(c.cluster1, ' - ', score1),
I might have not been clear enough in the spec, but I wasn't trying to say that you should omit all the other columns. I was just saying that the specified formatting should be applied to the specified columns, but the rest of the columns should still be included regularly with no specific formatting. Sorry if you misunderstood that. Pls. fix it so that it includes all the columns.

2024-01-01 21:24 UTC, Estyg100 commented on 1 Table.sql
> +    constraint ck_Date_of_birth_should_be_at_least_18_years_before_Date_first_consultation check(datediff(year, Dateofbirth, DateFoundJob) >= 18),
This was probably just a typo, but you wrote DateFoundJob, instead of DateFirstConsultation. Pls. fix that.

2024-01-02 22:07 UTC, ChavyWal commented on 1 Table.sql
> +DateFoundJob Date null ,
k I added  it to a constraint.

2024-01-02 22:08 UTC, ChavyWal commented on 1 Table.sql
> +    constraint ck_score2_cannot_be_lower_than_score3 check (score2 >= score3),
Thanks for the tip!

2024-01-02 22:09 UTC, ChavyWal commented on 1 Table.sql
> +        check((seekingjob = 1 and Datefoundjob is null) or (seekingjob = 0 and Datefoundjob is null) or (seekingjob = 0 and DateFoundJob is not null))
I actually do have a constraint for that.

2024-01-02 22:20 UTC, ChavyWal commented on 1 Table.sql
> +    constraint u_Phone_number_Has_to_be_unique unique,
k i did it

2024-01-02 22:20 UTC, ChavyWal commented on 1 Table.sql
> +    constraint ck_Date_of_birth_should_be_at_least_18_years_before_Date_first_consultation check(datediff(year, Dateofbirth, DateFoundJob) >= 18),
i think  i fixed that

2024-01-02 22:25 UTC, ChavyWal commented on 3 reports.sql
> +select fullname = CONCAT(c.lastname, ', ', c.Firstname), clusterscore1 = CONCAT(c.cluster1, ' - ', score1),
you actually did say i should include all in the question

2024-01-03 04:06 UTC, Estyg100 approved these changes
I Reviewed your work.
Excellent job!!!! Amazing!!!!!!
Since you got everything right on your second submission, **YOU GET100%!!!!**
I did write one tip, but there's no need to resubmit.

2024-01-03 04:06 UTC, Estyg100 commented on 1 Table.sql
> +    constraint ck_DateFirstConsultation_cannot_be_future_date check( DateFirstConsultation <= getdate()),
Tip: Technically you can combine these 2 constraints with an and, but no need to resubmit.

2024-01-03 04:08 UTC, closed without merging